<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Proyecto Z</title>
        <link rel="Shortcut Icon" href="favicon.ico"/>
        <script src="js/jquery-1.5.1.min.js" type="text/javascript"></script>
        <script src="js/jquery.validate.js" type="text/javascript"></script>
        <script src="js/jquery.dataTables.min.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="css/reset.css" />
        <link rel="stylesheet" type="text/css" href="css/base.css" />
    </head>
    <body>
        <div id="page-wrap">
            <div id="inside">
<!--                <div id="header">
                    header
                </div>-->
<!--                <div id="main">-->
                <div id="left-side">
                    <ul>
                        <li>Mensajes</li>
                        <li>Gente en la comunidad</li>
                        <li>Mis Amigos</li>
                        <li>Clasificados</li>
                        <li>Necesidades</li>
                        <li>Eventos</li>
                    </ul>
                </div>
                <div id="main-content">
                    <? include $cp->getCSec()->getLayout(); ?>
                </div>
                <div id="right-side">
                    der
                </div>
<!--                </div>-->
                <div style="clear: both;"></div>
            </div>
            <div style="clear: both;"></div>
        </div>
    </body>
</html>

