<?
$error = array("", "Usuario o contrase&ntilde;a incorrectos", "La contrase&ntilde;a fue enviada correctamente");
$tipoError = array("", "error", "success");
if (isset($_GET["e"])) {
    $msg = $error[$_GET["e"]];
    $tipoMsg = $tipoError[$_GET["e"]];
} else {
    $msg = "Complete los siguientes campos para ingresar";
    $tipoMsg = "information";
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
        <title>Proyecto Z</title>
        <script type="text/javascript" src="js/jquery-1.4.2.min.js"></script>
        <script src="js/jquery.validate.js" type="text/javascript"></script>
        <script type="text/javascript" src="js/login.js"></script>
    </head>
    <body>
        <div id="contenedor">
            <div id="contenido">
                <form action="?sec=log&do=in" method="post" id="formu">
                    <div class="notification <?=$tipoMsg;?> png_bg">
                        <div><?=$msg;?></div>
                    </div>
                    <p>
                        <label>Usuario:</label>
                        <input class="text-input medium-input required" type="text" name="user" value=""/>
                        <input type="hidden" name="emp" value="easton"/>
                    </p>
                    <div class="clear"></div>
                    <p>
                        <label>Contrase&ntilde;a:</label>
                        <input class="text-input medium-input required" type="password" name="pass" value=""/>
                    </p>
                    <div class="clear"></div>
                    <p>
                        <input class="button" type="submit" value="Entrar" />
                    </p>
                    <div class="clear"></div>
                </form>
            </div>
            
        </div>
    </body>
</html>